# Change these first
owner: SpecializedBicycles # Your GitHub organization or username, where this repository lives
repo: retul-uptime-monitor # The name of this repository

sites:
  - name: Premium Fit Health Check
    url: https://api.production.retul.com/premium-fit-service/health_check/
  - name: Retailer Roles Health Check
    url: https://api.production.retul.com/retailer-roles-service/health_check/
  - name: Retul at Home Health Check
    url: https://api.production.retul.com/retul-at-home-service/health_check/
  - name: Passport Health Check
    url: https://api.production.retul.com/passport-service/health_check/
  - name: Bike Sizing Service Health Check
    url: https://api.production.retul.com/bike-sizing-service/health_check/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /retul-uptime-monitor
  logoUrl: https://images.squarespace-cdn.com/content/v1/5926130fd482e9754a46296b/1496783195499-WJTPMMVIJSB7WKRL561Z/RetulLogo.png?format=1500w
  publish: true
  theme: dark
  name: Retül Services Uptime Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 0 * * *"
  uptime: "*/5 * * * *"




# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
